# Modifiez ce fichier pour qu'il corresponde à votre application
phpk_core:
  arborescence:
    Campagne:
      libelle: Mes Campagnes
      habilitations: [  DDQ_CONSULTE ]
      fils:
        Parking:
          route: campagnes_parking
          libelle: Parking
          habilitations:  [ DDQ_CONSULTE ]
        RTT:
          route: campagnes_rtt
          libelle: RTT
          habilitations: [ DDQ_CONSULTE ]
        Temps Partiel:
          route: campagnes_tp
          libelle: Temps Partiel
          habilitations: [ DDQ_CONSULTE ]
    #        Télétravail:
    #          libelle: Télétravail
    #          habilitations: [DDQ_CONSULTE]
    Historique:
      libelle: Historique
      habilitations: [DDQ_CONSULTE]
      fils:
        Parking:
          route: historique_parking
          libelle: Parking
          habilitations: [DDQ_CONSULTE]

        RTT:
          route: historique_rtt
          libelle: RTT
          habilitations: [ DDQ_CONSULTE ]

        Temps Partiel:
          route: historique_tp
          libelle: Temps Partiel
          habilitations: [ DDQ_CONSULTE ]

    #        Télétravail:
    #          libelle: Télétravail

    Validations:
      libelle: Validations
      habilitations: [DDQ_VALID]
      fils:
        Parking:
          habilitations: [DDQ_VAL_PARK]
          route: liste_questionnaires_parking
          libelle: Parking
        RTT:
          libelle: RTT
          fils:
            Niveau 1:
              route: liste_questionnaires_rtt
              libelle: Niveau 1
              habilitations: [ DDQ_VAL_RTT1 ]
            Niveau 1bis:
              route: liste_questionnaires_rttN1N2
              libelle: Niveau 1 Bis
              habilitations: [ DDQ_VAL_RTT1 ]
            Niveau 2:
              #route: liste_questionnaires_rttN+1
              libelle: Niveau 2
              habilitations: [ DDQ_VAL_RTT2 ]
              fils:
                Rtt_global:
                  libelle: Global
                  route: liste_questionnaires_rttN+1
                Branche Resssource:
                  libelle: Branche ressources
                  route: liste_questionnaires_rttN+1_branche_ressources
                Branche Sante:
                  libelle: Branche santé et affaires juridiques
                  route: liste_questionnaires_rttN+1_branche_sante
                Branche Production:
                  libelle: Branche production et relation client
                  route: liste_questionnaires_rttN+1_branche_prod
                Branche Financiere et comptable:
                  libelle: Branche financière et comptable
                  route: liste_questionnaires_rttN+1_branche_financiere
                Direction Generale:
                  libelle: Branche Direction Générale
                  route: liste_questionnaires_rttN+1_branche_direction
        Temps Partiel:
          libelle: Temps Partiel
          fils:
            Niveau 1:
              route: liste_questionnaires_tp
              libelle: Niveau 1
              habilitations: [ DDQ_VAL_TP1 ]
            Niveau 1 bis:
              route: liste_questionnaires_tpN1N2
              libelle: Niveau 1 Bis
              habilitations: [ DDQ_VAL_TP1 ]
            Niveau 2:
              route: liste_questionnaires_tpN+1
              libelle: Niveau 2
              habilitations: [ DDQ_VAL_TP2 ]
        Recensement:
          libelle: Recensement
          fils:
            Rencessement RH:
              habilitations: [ DDQ_RRH ]
              route: greve_agent
              libelle: Recenssement RH
            Rencessement Manager:
              libelle: Recensement Manager
              habilitations: [ DDQ_RRH ]


    Administration:
      libelle: Administration
      habilitations: [ DDQ_ADMIN ]
      fils:
        Nouvelle Campagne:
          route: nouvelle_campagne
          libelle: Nouvelle Campagne
        Clôture Campagne:
          route: cloture_campagne
          libelle: Clôture Campagne
        Parking:
          libelle: Parking
          habilitations: [ DDQ_ADMIN_PARK ]
          fils:
            Resultats:
              route: resultats_parking
              libelle: Résultats
              habilitations: [ DDQ_ADMIN_STAT ]
              # Stats:
              #    route : test
              #  libelle: Statistiques

            #                        Utilisateurs:
            #                            route: utilisateur_parking
            #                            libelle: Utilisateurs
            Userparking:
              route: user_park
              libelle: Utilisateurs
              habilitations: [ DDQ_ADMIN_UTIL ]
        RTT:
          libelle: RTT
          habilitations: [ DDQ_ADMIN_RTT ]
          fils:
            Resultats:
              route: resultats_rtt
              libelle: Résultats
            Rtt_global:
              libelle: Global
              route: adminRttGlobal
            Rtt_JourFixe39h00:
              libelle: 39h00 Jour fixe
              route: adminRtt39h00Fixe
            Rtt_quadrimestre39h00:
              libelle: 39h00 quadrimestre
              route: adminRtt39h00Quadrimestre
            Rtt_quadrimestre37h00:
              libelle: 37h00
              route: adminRtt37h00
            Rtt_quadrimestre36h00:
              libelle: 36h00
              route: adminRtt36h00
            Rtt_Non_Transmis:
              libelle: Non Transmis
              route: adminRttNonValide

        Temps Partiel:
          libelle: Temps Partiel
          habilitations: [ DDQ_ADMIN_TP ]
          fils:
            Resultats:
              route: resultats_tp
              libelle: Résultats
            Items:
              libelle: Gestion des Items
              route: ddqcontrat_index
              habilitations: [ DDQ_ADMIN_ITEM ]
            Tp_global:
              libelle: Global
              route: adminTpGlobal
        Recensement:
          libelle: Recensement
          habilitations: [ DDQ_RRH ]
          fils:
            Capmagne_ouverture:
              libelle: Nouveau Recensement
              route: admin_recensement_nouveau
              habilitations: [ DDQ_RRH ]
            Capmagne_cloture:
              libelle: Cloture Recensement
              route: admin_recensement_cloture
              habilitations: [ DDQ_RRH ]
            Liste des services:
              libelle: Liste des services
              route: admin_recensement_service
              habilitations: [ DDQ_RRH ]
            Manager:
              libelle: Manager
              habilitations: [ DDQ_RRH ]
            Droits:
              libelle: Gestion des droits
              habilitations: [ DDQ_RRH ]
            Statistiques:
              libelle: Statistiques
              habilitations: [ DDQ_RRH ]
            Greve_last:
              libelle: Dernière grève
              habilitations: [ DDQ_RRH ]
            Greve_Archives:
              libelle: Grèves archivées
              habilitations: [ DDQ_RRH ]



            #            Télétravail:
            #              libelle: Télétravail
            #              fils:
            #                Resultats:
            #                  route: resultats_tp
            #                  libelle: Résultats
            #                  habilitations: [ DDQ_ADMIN_STAT ]
            #                Items:
            #                  libelle: Gestion des Items
            #                  habilitations: [ DDQ_ADMIN_ITEM ]
            #                  #habilitations: [ DDQ_ADMIN_STAT ]
            #                Utilisateurs:
            #                  libelle: Utilisateurs


            # Structure :
            # <nom>:
            #     route: <identifiant de la route>
            #     libelle: <libellé du menu>
            #     habilitations: <tableau d'habilitations>
            #     fils: # 2 niveaux maximum en mode horizontal / 3 niveaux maximum en mode vertical
            #           <nom> ...
            #
            # Exemple :
            # exemple_sous_menu:
            #     libelle: Sous-menu
            #     habilitations: [ XXX_XXX ]
            #     fils:
            #         exemple_sous_menu1:
            #             libelle: Sous-menu 1
            #         exemple_sous_menu2:
            #             libelle: Sous-menu 2
            #             fils:
            #                 exemple_sous_menu21:
            #                     libelle: Sous-menu 21
            #                     route: <identifiant de la route>
            #                     menu: false # Permet d'indiquer que ce fils n'est pas un menu mais une simple page. Cela permet de gérer correctement le fil d'Ariane.
            #                 exemple_sous_menu22:
            #                     libelle: Sous-menu 22


# Vous pouvez également configurer phpk_core.interapplications et phpk_core.outils dans ce fichier si vous le souhaitez