<?php

namespace AppBundle\Repository\Entity;

/**
 * DdqQuestionnaireRrhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqQuestionnaireRrhRepository extends \Doctrine\ORM\EntityRepository
{
}
