<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entite extends \AppBundle\Entity\Entite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];


    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__ = $cloner;
    }


    /**
     *
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'nomentcomplet', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'nomentabrege', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'sigleent', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'direction', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'parent', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'nomorganisme', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'tel', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'idresponsable', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'nomresponsable', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'contact', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'nomcontact', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'rattachement', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'cheminphoto', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'idOrganisme', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'idSite'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'nomentcomplet', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'nomentabrege', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'sigleent', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'direction', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'parent', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'nomorganisme', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'tel', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'idresponsable', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'nomresponsable', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'contact', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'nomcontact', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'rattachement', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'cheminphoto', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'idOrganisme', '' . "\0" . 'AppBundle\\Entity\\Entite' . "\0" . 'idSite'];
    }

    /**
     *
     */
    public function __wakeup()
    {
        if (!$this->__isInitialized__) {
            $this->__initializer__ = function (Entite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if (!array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     *
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }


    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomentcomplet($nomentcomplet = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomentcomplet', [$nomentcomplet]);

        return parent::setNomentcomplet($nomentcomplet);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomentcomplet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomentcomplet', []);

        return parent::getNomentcomplet();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomentabrege($nomentabrege = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomentabrege', [$nomentabrege]);

        return parent::setNomentabrege($nomentabrege);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomentabrege()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomentabrege', []);

        return parent::getNomentabrege();
    }

    /**
     * {@inheritDoc}
     */
    public function setSigleent($sigleent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSigleent', [$sigleent]);

        return parent::setSigleent($sigleent);
    }

    /**
     * {@inheritDoc}
     */
    public function getSigleent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSigleent', []);

        return parent::getSigleent();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirection($direction = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirection', [$direction]);

        return parent::setDirection($direction);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirection', []);

        return parent::getDirection();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent($parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomorganisme($nomorganisme = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomorganisme', [$nomorganisme]);

        return parent::setNomorganisme($nomorganisme);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomorganisme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomorganisme', []);

        return parent::getNomorganisme();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdresponsable($idresponsable = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdresponsable', [$idresponsable]);

        return parent::setIdresponsable($idresponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdresponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdresponsable', []);

        return parent::getIdresponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomresponsable($nomresponsable = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomresponsable', [$nomresponsable]);

        return parent::setNomresponsable($nomresponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomresponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomresponsable', []);

        return parent::getNomresponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', [$contact]);

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', []);

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomcontact($nomcontact = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomcontact', [$nomcontact]);

        return parent::setNomcontact($nomcontact);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomcontact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomcontact', []);

        return parent::getNomcontact();
    }

    /**
     * {@inheritDoc}
     */
    public function setRattachement($rattachement = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRattachement', [$rattachement]);

        return parent::setRattachement($rattachement);
    }

    /**
     * {@inheritDoc}
     */
    public function getRattachement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRattachement', []);

        return parent::getRattachement();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheminphoto($cheminphoto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheminphoto', [$cheminphoto]);

        return parent::setCheminphoto($cheminphoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheminphoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheminphoto', []);

        return parent::getCheminphoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdOrganisme(\AppBundle\Entity\Organisme $idOrganisme = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdOrganisme', [$idOrganisme]);

        return parent::setIdOrganisme($idOrganisme);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdOrganisme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOrganisme', []);

        return parent::getIdOrganisme();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSite(\AppBundle\Entity\Site $idSite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSite', [$idSite]);

        return parent::setIdSite($idSite);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSite', []);

        return parent::getIdSite();
    }

}
