<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Organisme extends \AppBundle\Entity\Organisme implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];


    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__ = $cloner;
    }


    /**
     *
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'nomabrege', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'nomcomplet', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'codeorganisme', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'numucanss', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'typeorganisme', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'sitesiege', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'sitesgeographiques', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'idcti', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'nomcti', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'codegdp', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'nomdomaine', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'codecaisse'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'nomabrege', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'nomcomplet', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'codeorganisme', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'numucanss', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'typeorganisme', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'sitesiege', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'sitesgeographiques', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'idcti', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'nomcti', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'codegdp', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'nomdomaine', '' . "\0" . 'AppBundle\\Entity\\Organisme' . "\0" . 'codecaisse'];
    }

    /**
     *
     */
    public function __wakeup()
    {
        if (!$this->__isInitialized__) {
            $this->__initializer__ = function (Organisme $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if (!array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     *
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }


    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomabrege($nomabrege = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomabrege', [$nomabrege]);

        return parent::setNomabrege($nomabrege);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomabrege()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomabrege', []);

        return parent::getNomabrege();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomcomplet($nomcomplet = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomcomplet', [$nomcomplet]);

        return parent::setNomcomplet($nomcomplet);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomcomplet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomcomplet', []);

        return parent::getNomcomplet();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeorganisme($codeorganisme = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeorganisme', [$codeorganisme]);

        return parent::setCodeorganisme($codeorganisme);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeorganisme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeorganisme', []);

        return parent::getCodeorganisme();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumucanss($numucanss = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumucanss', [$numucanss]);

        return parent::setNumucanss($numucanss);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumucanss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumucanss', []);

        return parent::getNumucanss();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeorganisme($typeorganisme = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeorganisme', [$typeorganisme]);

        return parent::setTypeorganisme($typeorganisme);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeorganisme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeorganisme', []);

        return parent::getTypeorganisme();
    }

    /**
     * {@inheritDoc}
     */
    public function setSitesiege($sitesiege = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSitesiege', [$sitesiege]);

        return parent::setSitesiege($sitesiege);
    }

    /**
     * {@inheritDoc}
     */
    public function getSitesiege()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSitesiege', []);

        return parent::getSitesiege();
    }

    /**
     * {@inheritDoc}
     */
    public function setSitesgeographiques($sitesgeographiques = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSitesgeographiques', [$sitesgeographiques]);

        return parent::setSitesgeographiques($sitesgeographiques);
    }

    /**
     * {@inheritDoc}
     */
    public function getSitesgeographiques()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSitesgeographiques', []);

        return parent::getSitesgeographiques();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcti($idcti = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcti', [$idcti]);

        return parent::setIdcti($idcti);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcti()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcti', []);

        return parent::getIdcti();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomcti($nomcti = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomcti', [$nomcti]);

        return parent::setNomcti($nomcti);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomcti()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomcti', []);

        return parent::getNomcti();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodegdp($codegdp = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodegdp', [$codegdp]);

        return parent::setCodegdp($codegdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodegdp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodegdp', []);

        return parent::getCodegdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomdomaine($nomdomaine = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomdomaine', [$nomdomaine]);

        return parent::setNomdomaine($nomdomaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomdomaine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomdomaine', []);

        return parent::getNomdomaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodecaisse($codecaisse = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodecaisse', [$codecaisse]);

        return parent::setCodecaisse($codecaisse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodecaisse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodecaisse', []);

        return parent::getCodecaisse();
    }

}
