<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DdqContrat extends \AppBundle\Entity\DdqContrat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];


    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__ = $cloner;
    }


    /**
     *
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'tempspartiel', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'nbheures', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'horairecontractuel', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'actif', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'nbjours', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'nbdemiesjournees', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'horairecontrat'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'tempspartiel', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'nbheures', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'horairecontractuel', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'actif', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'nbjours', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'nbdemiesjournees', '' . "\0" . 'AppBundle\\Entity\\DdqContrat' . "\0" . 'horairecontrat'];
    }

    /**
     *
     */
    public function __wakeup()
    {
        if (!$this->__isInitialized__) {
            $this->__initializer__ = function (DdqContrat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if (!array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     *
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }


    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setActif($actif = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActif', [$actif]);

        return parent::setActif($actif);
    }

    /**
     * {@inheritDoc}
     */
    public function getActif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActif', []);

        return parent::getActif();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempspartiel($tempspartiel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempspartiel', [$tempspartiel]);

        return parent::setTempspartiel($tempspartiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempspartiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempspartiel', []);

        return parent::getTempspartiel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbheures($nbheures = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbheures', [$nbheures]);

        return parent::setNbheures($nbheures);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbheures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbheures', []);

        return parent::getNbheures();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorairecontractuel($horairecontractuel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorairecontractuel', [$horairecontractuel]);

        return parent::setHorairecontractuel($horairecontractuel);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorairecontractuel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorairecontractuel', []);

        return parent::getHorairecontractuel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbjours($nbjours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbjours', [$nbjours]);

        return parent::setNbjours($nbjours);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbjours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbjours', []);

        return parent::getNbjours();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbdemiesjournees($nbdemiesjournees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbdemiesjournees', [$nbdemiesjournees]);

        return parent::setNbdemiesjournees($nbdemiesjournees);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbdemiesjournees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbdemiesjournees', []);

        return parent::getNbdemiesjournees();
    }

    /**
     * {@inheritDoc}
     */
    public function sethorairecontrat($horairecontrat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sethorairecontrat', [$horairecontrat]);

        return parent::sethorairecontrat($horairecontrat);
    }

    /**
     * {@inheritDoc}
     */
    public function gethorairecontrat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gethorairecontrat', []);

        return parent::gethorairecontrat();
    }

}
