<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_js_routing.serializer' shared service.

include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/SerializerInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/NormalizerInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/DenormalizerInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Encoder/EncoderInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Encoder/DecoderInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/SerializerAwareInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/SerializerAwareTrait.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/SerializerAwareNormalizer.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/ObjectToPopulateTrait.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/GetSetMethodNormalizer.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Serializer/Encoder/JsonEncoder.php';

return $this->services['fos_js_routing.serializer'] = new \Symfony\Component\Serializer\Serializer([0 => new \Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer()], ['json' => new \Symfony\Component\Serializer\Encoder\JsonEncoder()]);
