<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'phpk_webservice.client.anr' shared service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-wsclient-bundle/DependencyInjection/Service/AnrService.php';

return $this->services['phpk_webservice.client.anr'] = new \CNAMTS\PHPK\WSClientBundle\DependencyInjection\Service\AnrService((($this->hasParameter("phpkws_client.anr")) ? ($this->getParameter("phpkws_client.anr")) : (null)), ${($_ = isset($this->services['monolog.logger.phpk_wsclient.anr']) ? $this->services['monolog.logger.phpk_wsclient.anr'] : $this->load('getMonolog_Logger_PhpkWsclient_AnrService.php')) && false ?: '_'});
