<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_security.user_provider' shared service.

include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/UserProviderInterface.php';
include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-security-bundle/Security/User/UserProvider.php';

return $this->services['phpk_security.user_provider'] = new \CNAMTS\PHPK\SecurityBundle\Security\User\UserProvider();
