<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_core.exception.listener' shared service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-core-bundle/Event/EventListener/ExceptionRequestEventListener.php';

return $this->services['phpk_core.exception.listener'] = new \CNAMTS\PHPK\CoreBundle\Event\EventListener\ExceptionRequestEventListener($this);
