<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_export.courrier' shared service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-export-bundle/DependencyInjection/Service/CourrierService.php';

return $this->services['phpk_export.courrier'] = new \CNAMTS\PHPK\ExportBundle\DependencyInjection\Service\CourrierService($this);
