<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_security.authapp' shared service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-security-bundle/DependencyInjection/Service/AuthAppService.php';

return $this->services['phpk_security.authapp'] = new \CNAMTS\PHPK\SecurityBundle\DependencyInjection\Service\AuthAppService(${($_ = isset($this->services['phpk_security.crypto']) ? $this->services['phpk_security.crypto'] : $this->load('getPhpkSecurity_CryptoService.php')) && false ?: '_'}, (($this->hasParameter("phpk_security.crypto.pkcs12_file")) ? ($this->getParameter("phpk_security.crypto.pkcs12_file")) : (null)), (($this->hasParameter("phpk_security.crypto.pkcs12_password")) ? ($this->getParameter("phpk_security.crypto.pkcs12_password")) : (null)), ${($_ = isset($this->services['monolog.logger.phpk_security.authapp']) ? $this->services['monolog.logger.phpk_security.authapp'] : $this->load('getMonolog_Logger_PhpkSecurity_AuthappService.php')) && false ?: '_'});
