<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_core.form.validator.nir' shared service.

include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidatorInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidator.php';
include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-core-bundle/Validator/Constraints/NirValidator.php';
include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-core-bundle/DependencyInjection/Service/ChecksumService.php';

return $this->services['phpk_core.form.validator.nir'] = new \CNAMTS\PHPK\CoreBundle\Validator\Constraints\NirValidator(${($_ = isset($this->services['phpk_core.cheksumChecker']) ? $this->services['phpk_core.cheksumChecker'] : ($this->services['phpk_core.cheksumChecker'] = new \CNAMTS\PHPK\CoreBundle\DependencyInjection\Service\ChecksumService())) && false ?: '_'});
