<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_webservice.client' shared service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-wsclient-bundle/DependencyInjection/Service/ClientService.php';

return $this->services['phpk_webservice.client'] = new \CNAMTS\PHPK\WSClientBundle\DependencyInjection\Service\ClientService((($this->hasParameter("phpkws_client")) ? ($this->getParameter("phpkws_client")) : (null)));
