<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_export.image' shared service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-export-bundle/DependencyInjection/Service/ExportService.php';
include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-export-bundle/DependencyInjection/Service/WkhtmlService.php';
include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-export-bundle/DependencyInjection/Service/ImageService.php';

return $this->services['phpk_export.image'] = new \CNAMTS\PHPK\ExportBundle\DependencyInjection\Service\ImageService($this);
