<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.guard.secured_area' shared service.

include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/AuthenticationProviderInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Security/Guard/Provider/GuardAuthenticationProvider.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/UserCheckerInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/UserChecker.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/UserProviderInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php';

return $this->services['security.authentication.provider.guard.secured_area'] = new \Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider(new RewindableGenerator(function () {
    yield 0 => ${($_ = isset($this->services['phpk.accessmaster_authenticator']) ? $this->services['phpk.accessmaster_authenticator'] : ($this->services['phpk.accessmaster_authenticator'] = new \CNAMTS\PHPK\SecurityBundle\Authenticator\AccessMasterAuthenticator($this))) && false ?: '_'};
    yield 1 => ${($_ = isset($this->services['phpk.bouchon_authenticator']) ? $this->services['phpk.bouchon_authenticator'] : ($this->services['phpk.bouchon_authenticator'] = new \CNAMTS\PHPK\SecurityBundle\Authenticator\BouchonAuthenticator($this))) && false ?: '_'};
}, 2), ${($_ = isset($this->services['security.user.provider.concrete.in_memory']) ? $this->services['security.user.provider.concrete.in_memory'] : ($this->services['security.user.provider.concrete.in_memory'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([]))) && false ?: '_'}, 'secured_area', new \Symfony\Component\Security\Core\User\UserChecker());
