<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.6ugztcq' shared service.

return $this->services['service_locator.6ugztcq'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['mailer' => function () {
    return ${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load('getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'};
}, 'test' => function () {
    $f = function (\AppBundle\Service\ContactService $v = null) {
        return $v;
    };
    return $f(${($_ = isset($this->services['AppBundle\Service\ContactService']) ? $this->services['AppBundle\Service\ContactService'] : $this->load('getContactServiceService.php')) && false ?: '_'});
}]);
