<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_snappy.pdf.internal_generator' shared service.

include_once $this->targetDirs[3] . '/vendor/knplabs/knp-snappy/src/Knp/Snappy/GeneratorInterface.php';
include_once $this->targetDirs[3] . '/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php';
include_once $this->targetDirs[3] . '/vendor/knplabs/knp-snappy/src/Knp/Snappy/Pdf.php';

return $this->services['knp_snappy.pdf.internal_generator'] = new \Knp\Snappy\Pdf('../bin/wkhtmltopdf-amd64', [], NULL);
