<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_core.tableau' shared service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-core-bundle/DependencyInjection/Service/TableauService.php';

return $this->services['phpk_core.tableau'] = new \CNAMTS\PHPK\CoreBundle\DependencyInjection\Service\TableauService($this);
