<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_webservice.client.soap' shared service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-wsclient-bundle/DependencyInjection/Service/SoapService.php';

return $this->services['phpk_webservice.client.soap'] = new \CNAMTS\PHPK\WSClientBundle\DependencyInjection\Service\SoapService((($this->hasParameter("phpkws_client.soap")) ? ($this->getParameter("phpkws_client.soap")) : (null)), ${($_ = isset($this->services['monolog.logger.phpk_wsclient.soap']) ? $this->services['monolog.logger.phpk_wsclient.soap'] : $this->load('getMonolog_Logger_PhpkWsclient_SoapService.php')) && false ?: '_'}, ${($_ = isset($this->services['phpk_security.authapp']) ? $this->services['phpk_security.authapp'] : $this->load('getPhpkSecurity_AuthappService.php')) && false ?: '_'});
