<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_security.crypto' shared service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-security-bundle/DependencyInjection/Service/CryptoService.php';

return $this->services['phpk_security.crypto'] = new \CNAMTS\PHPK\SecurityBundle\DependencyInjection\Service\CryptoService($this, ${($_ = isset($this->services['monolog.logger.phpk_security.crypto']) ? $this->services['monolog.logger.phpk_security.crypto'] : $this->load('getMonolog_Logger_PhpkSecurity_CryptoService.php')) && false ?: '_'});
