<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_core.form.extension.button' shared service.

include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractTypeExtension.php';
include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-core-bundle/Form/Extension/ButtonExtension.php';

return $this->services['phpk_core.form.extension.button'] = new \CNAMTS\PHPK\CoreBundle\Form\Extension\ButtonExtension($this);
