<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_security.bouchon' shared service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-security-bundle/DependencyInjection/Service/BouchonService.php';

return $this->services['phpk_security.bouchon'] = new \CNAMTS\PHPK\SecurityBundle\DependencyInjection\Service\BouchonService($this);
