<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpk_core.form.type.autocompletion' shared service.

include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3] . '/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-core-bundle/Form/Type/AutocompletionType.php';

return $this->services['phpk_core.form.type.autocompletion'] = new \CNAMTS\PHPK\CoreBundle\Form\Type\AutocompletionType();
