<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Table\TableRttAgent' shared autowired service.

include_once $this->targetDirs[3] . '/vendor/cnamts/phpk/bundles/phpk-core-bundle/Generator/Table/TableGenerator.php';
include_once $this->targetDirs[3] . '/src/AppBundle/Table/TableRttAgent.php';

return $this->services['AppBundle\Table\TableRttAgent'] = new \AppBundle\Table\TableRttAgent();
