<?php

namespace AppBundle\Repository;
/**
 * AnrAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnrAgentRepository extends \Doctrine\ORM\EntityRepository
{
}
