<?php

namespace AppBundle\Repository;
/**
 * AnrEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnrEntiteRepository extends \Doctrine\ORM\EntityRepository
{
}
