<?php

namespace AppBundle\Repository;
/**
 * AnrOrganismeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnrOrganismeRepository extends \Doctrine\ORM\EntityRepository
{
}
