<?php

namespace AppBundle\Repository;
/**
 * AnrSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnrSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
