<?php

namespace AppBundle\Repository;
/**
 * DdqCampagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqCampagneRepository extends \Doctrine\ORM\EntityRepository
{
    public function liste()
    {
        $qb = $this->createQueryBuilder('a');
        return $qb;
    }

    public function findByStatutQueryBuilder($statut)
    {
        $query = $this->createQueryBuilder('a');
        $query->where('a.statut!=:statut')
            ->setParameter('statut', $statut);
        return $query;
    }

    public function findByCategorieQueryBuilder($categorie)
    {
        $query = $this->createQueryBuilder('c');
        $query->join('c.idDdqCategorie', 'cat')
            ->where('cat.libelle=:libelle')
            ->orderBy('c.datefin', 'DESC');
        $query->setParameter('libelle', $categorie);
        return $query;
    }


}
