<?php

namespace AppBundle\Repository;
/**
 * DdqContratRepartitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqContratRepartitionRepository extends \Doctrine\ORM\EntityRepository
{
}
