<?php

namespace AppBundle\Repository;
/**
 * DdqCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
