<?php

namespace AppBundle\Repository;
/**
 * DdqContratRepartitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use CNAMTS\PHPK\CoreBundle\Data\Repository;

class DdqContratRepartitionRepository extends \Doctrine\ORM\EntityRepository implements Repository
{
    public function liste()
    {
        $qb = $this->createQueryBuilder('a');
        return $qb;
    }

    public function findOneByContrat($idContrat)
    {
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqContratRepartition q '
            . 'WHERE q.idDdqContrat = :idContrat');
        $query->setParameter('idContrat', $idContrat);

        return $query->getSingleResult();

    }

    public function findByRepartition($parameters)
    {


        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqContratRepartition q
         
             ');
        // $query->setParameter('idContrat',$parameters);
        //dump($query);

        return $query->getResult();


        /*$query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireTp q '
            . 'JOIN q.idDdqCampagne c '
            . 'WHERE c.statut = \'nouvelle\' '
            . 'AND q.idAgent = :idAgent');
        $query->setParameter('idAgent', $parameters[0]);
        return $query->getResult();*/
    }
}
