<?php

namespace AppBundle\Repository;
/**
 * DdqContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use CNAMTS\PHPK\CoreBundle\Data\Repository;

class DdqContratRepository extends \Doctrine\ORM\EntityRepository implements Repository
{
    public function liste()
    {
        $qb = $this->createQueryBuilder('a');
        return $qb;
    }

    public function getByTempsPartielQueryBuilder($tempspartiel)
    {
        $query = $this->createQueryBuilder('a');
        $query->where('a.tempspartiel = :tempspartiel')
            ->orderBy('a.nbheures', 'DESC')
            ->setParameter('tempspartiel', $tempspartiel);
        return $query;
    }

    public function findByTempsPlein()
    {
        $query = $this->_em->createQuery(
            'SELECT c FROM AppBundle:DdqContrat c '
            . 'WHERE c.tempspartiel = false');
        return $query->getResult();
    }

    public function findByTempsPartiel()
    {
        $query = $this->_em->createQuery(
            'SELECT c FROM AppBundle:DdqContrat c '
            . 'WHERE c.tempspartiel = true');
        return $query->getResult();
    }
}
