<?php

namespace AppBundle\Repository;
/**
 * DdqHorraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqHorraireRepository extends \Doctrine\ORM\EntityRepository
{
}
