<?php

namespace AppBundle\Repository;
/**
 * DdqHorraireRepartitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqHorraireRepartitionRepository extends \Doctrine\ORM\EntityRepository
{
}
