<?php

namespace AppBundle\Repository;

use CNAMTS\PHPK\CoreBundle\Data\Repository;

/**
 * DdqQuestionnaireRttRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqQuestionnaireRttRepository extends \Doctrine\ORM\EntityRepository implements Repository
{
    public function liste()
    {
        $qb = $this->createQueryBuilder('a');
        return $qb;
    }

    public function findOneByAgentByCampagne($agent, $campagne)
    {
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idDdqCampagne c '
            . 'WHERE c.libelle = :campagne '
            . 'AND q.idAgent = :idAgent');
        $query->setParameter('campagne', $campagne);
        $query->setParameter('idAgent', $agent);
        return $query->getSingleResult();
    }

    public function findByMesCampagnes(array $parameters)
    {
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idDdqCampagne c '
            . 'WHERE c.statut = \'nouvelle\' '
            . 'AND q.idAgent = :idAgent');
        $query->setParameter('idAgent', $parameters[0]);
        return $query->getResult();
    }

    public function findByMesCampagnesTerminees(array $parameters)
    {
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idDdqCampagne c '
            . 'WHERE c.statut = \'terminée\' '
            . 'AND q.idAgent = :idAgent');
        $query->setParameter('idAgent', $parameters[0]);
        return $query->getResult();
    }

    public function findByQuestionnairesRemplis(array $parameters)
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameter = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE a.idresponsable = :nomresponsable '
            . ' AND q.idDdqCampagne = :IdCampagneEnCours '
            . 'AND q.statut = \'etape6\'');
        //OR q.statut = \'validé N+1\''
        $query->setParameter('nomresponsable', $parameters[0]);
        $query->setParameter('IdCampagneEnCours', $parameter);
        return $query->getResult();
    }

    public function findByQuestionnairesRemplisN1(array $parameters)
    {
        /*
        Ancienne Requête
        $query = $this->_em->createQuery(
            'SELECT q FROM  AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE a.sigleent LIKE :sigleent '
            . 'AND q.statut = \'validé N+1\'');*/
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM  AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE  q.statut = \'validé N+1\' '
            . ' AND q.idDdqCampagne = :IdCampagneEnCours');

        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findByQuestionnairesRemplisN1N2(array $parameters)
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        ($parameter = ($query0->getResult()[0]));
        ($sigleent = $parameters[0]);
        ($sigleent2 = substr($sigleent, 0, 11));
        $query1 = $this->_em->createQuery(
            'SELECT q FROM  AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE a.sigleent LIKE :sigleent '
            . ' AND q.idDdqCampagne = :IdCampagneEnCours '
            . 'AND q.statut  LIKE \'%etape6%\'');
        $query1->setParameter('sigleent', $sigleent . '%');
        $query1->setParameter('IdCampagneEnCours', $parameter);
        return $query1->getResult();
    }

    public function findByQuestionnairesRemplisN1BrancheRessources(array $parameters)
    {
        //$sigleent =substr($parameters[0],0 ,11);
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $sigleent = '/DIR/SD-ADM';
        $query1 = $this->_em->createQuery(
            'SELECT q FROM  AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE a.sigleent LIKE :sigleent '
            . ' AND q.idDdqCampagne = :IdCampagneEnCours '
            . 'AND q.statut = \'validé N+1\'');
        $query1->setParameter('sigleent', $sigleent . '%');
        $query1->setParameter('IdCampagneEnCours', $parameters);
        //dump($query1->getresult());
        return $query1->getResult();
    }

    public function findByQuestionnairesRemplisN1BrancheSante(array $parameters)
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $sigleent = '/DIR/DA/';
        $query1 = $this->_em->createQuery(
            'SELECT q FROM  AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE a.sigleent LIKE :sigleent '
            . ' AND q.idDdqCampagne = :IdCampagneEnCours '
            . 'AND q.statut = \'validé N+1\'');
        $query1->setParameter('sigleent', '%' . $sigleent . '%');
        $query1->setParameter('IdCampagneEnCours', $parameters);
        return $query1->getResult();
    }

    public function findByQuestionnairesRemplisN1BrancheProd(array $parameters)
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $sigleent = '/DIR/DA-PROD/';
        $query1 = $this->_em->createQuery(
            'SELECT q FROM  AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE a.sigleent LIKE :sigleent '
            . ' AND q.idDdqCampagne = :IdCampagneEnCours '
            . 'AND q.statut = \'validé N+1\'');
        $query1->setParameter('sigleent', $sigleent . '%');
        $query1->setParameter('IdCampagneEnCours', $parameters);
        return $query1->getResult();
    }

    public function findByQuestionnairesRemplisN1BrancheFinance(array $parameters)
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $sigleent = '/DIR/DIR-FIIN-COMPTA';
        $query1 = $this->_em->createQuery(
            'SELECT q FROM  AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE a.sigleent LIKE :sigleent '
            . ' AND q.idDdqCampagne = :IdCampagneEnCours '
            . 'AND q.statut = \'validé N+1\'');
        $query1->setParameter('sigleent', $sigleent . '%');
        $query1->setParameter('IdCampagneEnCours', $parameters);
        //  dump($query1->getResult());
        return $query1->getResult();
    }

    public function findByQuestionnairesRemplisN1BrancheDirection(array $parameters)
    {

        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameter = ($query0->getResult()[0]);
        $sigleent = "/DIR/SD-ADM";
        $sigleent2 = '/DIR/DA';
        $sigleent3 = '/DIR/DA-PROD';
        $sigleent4 = '/DIR/DIR-FIIN-COMPTA';
        $query1 = $this->_em->createQuery(
            'SELECT q FROM  AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE a.sigleent NOT LIKE :sigleent '
            . 'AND a.sigleent NOT LIKE :sigleent2 '
            . 'AND a.sigleent NOT LIKE :sigleent3 '
            . 'AND a.sigleent NOT LIKE :sigleent4 '
            . ' AND q.idDdqCampagne = :IdCampagneEnCours '
            . 'AND q.statut = \'validé N+1\'');
        $query1->setParameter('sigleent', '%' . $sigleent . '%');
        $query1->setParameter('sigleent2', '%' . $sigleent2 . '%');
        $query1->setParameter('sigleent3', '%' . $sigleent3 . '%');
        $query1->setParameter('sigleent4', '%' . $sigleent4 . '%');
        $query1->setParameter('IdCampagneEnCours', $parameter);
        //  dump($query1->getResult());
        return $query1->getResult();
    }

    public function countByNbTotal($idCampagne)
    {
        $query = $this->_em->createQuery(
            'SELECT COUNT(q) FROM AppBundle:DdqQuestionnaireRtt q '
            . 'WHERE q.idDdqCampagne = :idCampagne');
        $query->setParameter('idCampagne', $idCampagne);
        return $query->getSingleScalarResult();
    }

    public function countByValid($idCampagne)
    {
        $query = $this->_em->createQuery(
            'SELECT COUNT(q) FROM AppBundle:DdqQuestionnaireRtt q '
            . 'WHERE q.idDdqCampagne = :idCampagne '
            . 'AND q.statut = \'validé N+2\'');
        $query->setParameter('idCampagne', $idCampagne);
        return $query->getSingleScalarResult();
    }

    public function countByInvalid($idCampagne)
    {
        $query = $this->_em->createQuery(
            'SELECT COUNT(q) FROM AppBundle:DdqQuestionnaireRtt q '
            . 'WHERE q.idDdqCampagne = :idCampagne '
            . 'AND q.statut = \'invalidé N+1\' '
            . 'OR q.statut = \'invalidé N+2\'');
        $query->setParameter('idCampagne', $idCampagne);
        return $query->getSingleScalarResult();
    }

    public function findAll()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q WHERE q.idDdqCampagne = :IdCampagneEnCours');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findBy39hJoursFixes()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q WHERE q.idDdqContrat=2 and q.formule= true AND q.idDdqCampagne = :IdCampagneEnCours');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findBy39hQuadrimestre()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q WHERE q.idDdqContrat=2 and q.formule= false AND q.idDdqCampagne = :IdCampagneEnCours');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findBy37h00()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q WHERE q.idDdqContrat=3 and q.formule= false AND q.idDdqCampagne = :IdCampagneEnCours ');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findBy36h00()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q WHERE q.idDdqContrat=4 and q.formule= false AND q.idDdqCampagne = :IdCampagneEnCours ');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findByNonValide()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        // dump($parameters);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q  WHERE q.statut <> \'validé N+2\' AND q.idDdqCampagne = :IdCampagneEnCours ');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }
}