<?php

namespace AppBundle\Repository;

use CNAMTS\PHPK\CoreBundle\Data\Repository;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqQuestionnaireRrhRepository extends \Doctrine\ORM\EntityRepository implements Repository
{
    public function liste()
    {
        $qb = $this->createQueryBuilder('a');
        return $qb;
    }

    public function findOneByNomium($nomium)
    {
        $query = $this->_em->createQuery('SELECT a FROM AppBundle:Agent a WHERE a.nomium = :nomium');
        $query->setParameter('nomium', $nomium);
        return $query->getSingleResult();
    }
}
