<?php

namespace AppBundle\Repository;

use CNAMTS\PHPK\CoreBundle\Data\Repository;

/**
 * DdqQuestionnaireRttRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqQuestionnaireRttRepository extends \Doctrine\ORM\EntityRepository implements Repository
{
    public function liste()
    {
        $qb = $this->createQueryBuilder('a');
        return $qb;
    }

    public function findOneByAgentByCampagne($agent, $campagne)
    {
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idDdqCampagne c '
            . 'WHERE c.libelle = :campagne '
            . 'AND q.idAgent = :idAgent');
        $query->setParameter('campagne', $campagne);
        $query->setParameter('idAgent', $agent);
        return $query->getSingleResult();
    }

    public function findByMesCampagnes(array $parameters)
    {
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idDdqCampagne c '
            . 'WHERE c.statut = \'nouvelle\' '
            . 'AND q.idAgent = :idAgent');
        $query->setParameter('idAgent', $parameters[0]);
        return $query->getResult();
    }

    public function findByMesCampagnesTerminees(array $parameters)
    {
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idDdqCampagne c '
            . 'WHERE c.statut = \'terminée\' '
            . 'AND q.idAgent = :idAgent');
        $query->setParameter('idAgent', $parameters[0]);
        return $query->getResult();
    }

    public function findByQuestionnairesRemplis(array $parameters)
    {
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE a.nomentabrege = :nomentabrege '
            . 'AND q.statut = \'etape6\'');
        $query->setParameter('nomentabrege', $parameters[0]);
        return $query->getResult();
    }

    public function findByQuestionnairesRemplisN1(array $parameters)
    {
        $query = $this->_em->createQuery(
            'SELECT q FROM  AppBundle:DdqQuestionnaireRtt q '
            . 'JOIN q.idAgent a '
            . 'WHERE a.sigleent LIKE :sigleent '
            . 'AND q.statut = \'validé N+1\'');
        $query->setParameter('sigleent', $parameters[0] . '%');
        return $query->getResult();
    }

    public function countByNbTotal($idCampagne)
    {
        $query = $this->_em->createQuery(
            'SELECT COUNT(q) FROM AppBundle:DdqQuestionnaireRtt q '
            . 'WHERE q.idDdqCampagne = :idCampagne');
        $query->setParameter('idCampagne', $idCampagne);
        return $query->getSingleScalarResult();
    }

    public function countByValid($idCampagne)
    {
        $query = $this->_em->createQuery(
            'SELECT COUNT(q) FROM AppBundle:DdqQuestionnaireRtt q '
            . 'WHERE q.idDdqCampagne = :idCampagne '
            . 'AND q.statut = \'validé N+2\'');
        $query->setParameter('idCampagne', $idCampagne);
        return $query->getSingleScalarResult();
    }

    public function countByInvalid($idCampagne)
    {
        $query = $this->_em->createQuery(
            'SELECT COUNT(q) FROM AppBundle:DdqQuestionnaireRtt q '
            . 'WHERE q.idDdqCampagne = :idCampagne '
            . 'AND q.statut = \'invalidé N+1\' '
            . 'OR q.statut = \'invalidé N+2\'');
        $query->setParameter('idCampagne', $idCampagne);
        return $query->getSingleScalarResult();
    }

    public function findAll()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q WHERE q.idDdqCampagne = :IdCampagneEnCours');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findBy39hJoursFixes()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q WHERE q.idDdqContrat=2 and q.formule= true AND q.idDdqCampagne = :IdCampagneEnCours');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findBy39hQuadrimestre()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q WHERE q.idDdqContrat=2 and q.formule= false AND q.idDdqCampagne = :IdCampagneEnCours');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findBy37h00()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q WHERE q.idDdqContrat=3 and q.formule= false AND q.idDdqCampagne = :IdCampagneEnCours ');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findBy36h00()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q WHERE q.idDdqContrat=4 and q.formule= false AND q.idDdqCampagne = :IdCampagneEnCours ');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }

    public function findByNonValide()
    {
        $query0 = $this->_em->createQuery(
            'SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRtt c');
        $parameters = ($query0->getResult()[0]);
        // dump($parameters);
        $query = $this->_em->createQuery(
            'SELECT q FROM AppBundle:DdqQuestionnaireRtt q  WHERE q.statut <> \'validé N+2\' AND q.idDdqCampagne = :IdCampagneEnCours ');
        $query->setParameter('IdCampagneEnCours', $parameters);
        return $query->getResult();
    }
}