<?php

namespace AppBundle\Repository;

use CNAMTS\PHPK\CoreBundle\Data\Repository;

/**
 * DdqQuestionnaireRrhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqQuestionnaireRrhRepository extends \Doctrine\ORM\EntityRepository implements Repository
{
    public function liste()
    {
        $qb = $this->createQueryBuilder('a');
        return $qb;
    }

    public function findOneByNomium($nomium)
    {
        $query = $this->_em->createQuery('SELECT a FROM AppBundle:Agent a WHERE a.nomium = :nomium');
        $query->setParameter('nomium', $nomium);
        return $query->getSingleResult();
    }

    public function findByServiceRrh(array $parameters)
    {
        $query0 = $this->_em->createQuery('SELECT MAX(c.idDdqCampagne) FROM AppBundle:DdqQuestionnaireRrh c');
        ($parameter = ($query0->getResult()[0]));
        $query = $this->_em->createQuery('SELECT  DISTINCT (b.nomentcomplet) FROM AppBundle:DdqQuestionnaireRrh q '
            . ' JOIN q.idAgent a'
            . ' JOIN q.idEntite b'
            . ' WHERE q.idDdqCampagne = :IdCampagneEnCours '
            . ' AND q.Modification = \'personne\''
            . ' AND q.idEntite is not null'
            . ' ORDER BY b.nomentcomplet ASC'
        );
        $query->setParameter('IdCampagneEnCours', $parameter);
        return $query->getResult();

    }
}
