<?php

namespace AppBundle\Repository;
/**
 * DdqRepartitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqRepartitionRepository extends \Doctrine\ORM\EntityRepository
{
}
