<?php

namespace AppBundle\Repository;
/**
 * DdqReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdqReglementRepository extends \Doctrine\ORM\EntityRepository
{
}
