<?php

namespace AppBundle\Repository;

use CNAMTS\PHPK\CoreBundle\Data\Repository;

/**
 * droitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class droitsRepository extends \Doctrine\ORM\EntityRepository implements Repository
{
}
