<?php

namespace AppBundle\Repository;

/**
 * TestjujuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestjujuRepository extends \Doctrine\ORM\EntityRepository
{
}
