<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP69guuk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__ . '/ContainerP69guuk/appDevDebugProjectContainer.php') {
    touch(__DIR__ . '/ContainerP69guuk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerP69guuk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerP69guuk\appDevDebugProjectContainer([
    'container.build_hash' => 'P69guuk',
    'container.build_id' => '8e35cc54',
    'container.build_time' => 1562059027,
], __DIR__ . \DIRECTORY_SEPARATOR . 'ContainerP69guuk');
